name: SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: windows-latest
    env:
      DOTNET_VERSION: '7.0.x'
      SONAR_PROJECT_KEY: AnFengTEC_ACS
      SONAR_ORG: anfengtec

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.NetWebBuildTools"

      - name: Install required workloads
        run: |
          dotnet workload install wasm-tools

      - name: Setup SonarCloud Scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory -Force
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner --version 5.13.0

      - name: Initialize SonarQube Scanner
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"${{ env.SONAR_PROJECT_KEY }}" `
            /o:"${{ env.SONAR_ORG }}" `
            /d:sonar.token="${{ env.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.scanner.skipJreProvisioning=true `
            /d:sonar.scanAll=false `
            /d:sonar.verbose=true

      - name: Build solution
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Complete SonarQube Scan
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"